### ISSUE TITLE
Linux - selected area doesn't match what gets recorded

### ISSUE THREAD

**Issue by dsandstrom** [lexcast/screen-recorder#3]
When I select an area to record, the highlighted area doesn't match where my cursor is.  The area is down and right.  However, the actual recording is done where my cursors were.  So, I have to watch where my cursor starts and ends, not the highlighted area.

**Comment by lexcast** [comment]
I forgot that issue, is on Windows or Linux?

**Comment by dsandstrom** [comment]
Linux.  I haven't tried it on others.

**Comment by lexcast** [comment]
which distro?

**Comment by dsandstrom** [comment]
Manjaro with Cinnamon 3.0.1, ffmpeg 3.0.2, and imagemagick 6.9.3.10

**Comment by lexcast** [comment]
I'm using ubuntu and works well enough. I remember that issue and I've fixed for my lap, I really don't know why the OS changes too much the way to get coordinates in a chrome window. Atom should normalize this for all OS.

Anyway, I have no way to fix on Cinnamon, if you want to try, check out the select-area-view or the linux adapter.

**Comment by dirk-thomas** [comment]
I ran into the same problem on Ubuntu 16.04. The recorded viewport was always further up and left than expected. And the size was always smaller than expected. Since I have a 4k display on a 15" screen I am using a scaling factor in the display settings.

After some debugging I am confident that the coordinates used to identify the top left corner, the width and height as well as the offset of the menubar all need to be scaled with [window.devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio). After modifying the code to apply the pixel ratio as a scaling factor to all of these coordinates the recorded viewport seems to be correct (tried with "window" as well as "manual selection"). Please see #9 for the PR containing the proposed changes.

**Comment by lexcast** [comment]
With #9 this should be fixed.
